//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actividades
    {
        public Actividades()
        {
            this.Permisos_Cuentas_x_Actividades = new HashSet<Permisos_Cuentas_x_Actividades>();
            this.Permisos_Perfiles_x_Actividades = new HashSet<Permisos_Perfiles_x_Actividades>();
            this.AreasDeTrabajo = new HashSet<AreasDeTrabajo>();
            this.Paginas = new HashSet<Paginas>();
        }
    
        public short Id_Actividad { get; set; }
        public string Nombre { get; set; }
        public bool Estatus { get; set; }
        public byte Id_Directorio { get; set; }
        public byte Id_Sistema { get; set; }
    
        public virtual Directorios Directorios { get; set; }
        public virtual Sistemas Sistemas { get; set; }
        public virtual ICollection<Permisos_Cuentas_x_Actividades> Permisos_Cuentas_x_Actividades { get; set; }
        public virtual ICollection<Permisos_Perfiles_x_Actividades> Permisos_Perfiles_x_Actividades { get; set; }
        public virtual ICollection<AreasDeTrabajo> AreasDeTrabajo { get; set; }
        public virtual ICollection<Paginas> Paginas { get; set; }
    }
}
