//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreasDeTrabajo
    {
        public AreasDeTrabajo()
        {
            this.Permisos_AreaDeTrabajo_x_Cuenta = new HashSet<Permisos_AreaDeTrabajo_x_Cuenta>();
            this.Actividades = new HashSet<Actividades>();
            this.Perfiles = new HashSet<Perfiles>();
            this.Beneficio = new HashSet<Beneficio>();
        }
    
        public short Id_AreaDeTrabajo { get; set; }
        public string Nombre { get; set; }
        public byte Id_Sistema { get; set; }
    
        public virtual Sistemas Sistemas { get; set; }
        public virtual ICollection<Permisos_AreaDeTrabajo_x_Cuenta> Permisos_AreaDeTrabajo_x_Cuenta { get; set; }
        public virtual ICollection<Actividades> Actividades { get; set; }
        public virtual ICollection<Perfiles> Perfiles { get; set; }
        public virtual ICollection<Beneficio> Beneficio { get; set; }
    }
}
