//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreasDeTrabajo
    {
        public AreasDeTrabajo()
        {
            this.AreasDeTrabajo_x_Perfiles = new HashSet<AreasDeTrabajo_x_Perfiles>();
            this.Beneficio_x_AreaDeTrabajo = new HashSet<Beneficio_x_AreaDeTrabajo>();
            this.Controlador_x_AreasDeTrabajo = new HashSet<Controlador_x_AreasDeTrabajo>();
            this.Controladores_x_AreasDeTrabajo = new HashSet<Controladores_x_AreasDeTrabajo>();
            this.Cuenta_x_AreasDeTrabajo_x_Accion = new HashSet<Cuenta_x_AreasDeTrabajo_x_Accion>();
        }
    
        public short Id_AreaDeTrabajo { get; set; }
        public string Nombre { get; set; }
        public byte Id_Sistema { get; set; }
    
        public virtual Sistemas Sistemas { get; set; }
        public virtual ICollection<AreasDeTrabajo_x_Perfiles> AreasDeTrabajo_x_Perfiles { get; set; }
        public virtual ICollection<Beneficio_x_AreaDeTrabajo> Beneficio_x_AreaDeTrabajo { get; set; }
        public virtual ICollection<Controlador_x_AreasDeTrabajo> Controlador_x_AreasDeTrabajo { get; set; }
        public virtual ICollection<Controladores_x_AreasDeTrabajo> Controladores_x_AreasDeTrabajo { get; set; }
        public virtual ICollection<Cuenta_x_AreasDeTrabajo_x_Accion> Cuenta_x_AreasDeTrabajo_x_Accion { get; set; }
    }
}
