//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficio_tipo
    {
        public Beneficio_tipo()
        {
            this.Beneficio = new HashSet<Beneficio>();
        }
    
        public byte Id_BeneficioTipo { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Beneficio> Beneficio { get; set; }
    }
}
