//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficio
    {
        public Beneficio()
        {
            this.Beneficio_x_AreaDeTrabajo = new HashSet<Beneficio_x_AreaDeTrabajo>();
            this.Beneficio_x_Perfiles = new HashSet<Beneficio_x_Perfiles>();
            this.Benficio_x_Cuenta = new HashSet<Benficio_x_Cuenta>();
            this.Parametros_x_Beneficio = new HashSet<Parametros_x_Beneficio>();
            this.ParametrosGpo_x_Beneficio = new HashSet<ParametrosGpo_x_Beneficio>();
        }
    
        public byte Id_Beneficio { get; set; }
        public string Nombre { get; set; }
        public byte Id_BeneficioTipo { get; set; }
        public bool Estatus { get; set; }
    
        public virtual Beneficio_tipo Beneficio_tipo { get; set; }
        public virtual ICollection<Beneficio_x_AreaDeTrabajo> Beneficio_x_AreaDeTrabajo { get; set; }
        public virtual ICollection<Beneficio_x_Perfiles> Beneficio_x_Perfiles { get; set; }
        public virtual ICollection<Benficio_x_Cuenta> Benficio_x_Cuenta { get; set; }
        public virtual ICollection<Parametros_x_Beneficio> Parametros_x_Beneficio { get; set; }
        public virtual ICollection<ParametrosGpo_x_Beneficio> ParametrosGpo_x_Beneficio { get; set; }
    }
}
