//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Benficio_x_Cuenta
    {
        public int Id_BeneficioCuenta { get; set; }
        public int Id_Cuenta { get; set; }
        public byte Id_Beneficio { get; set; }
        public bool Estatus { get; set; }
    
        public virtual Beneficio Beneficio { get; set; }
        public virtual Cuentas Cuentas { get; set; }
    }
}
