//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Controladores
    {
        public Controladores()
        {
            this.Accion_x_Controlador = new HashSet<Accion_x_Controlador>();
            this.Controlador_x_AreasDeTrabajo = new HashSet<Controlador_x_AreasDeTrabajo>();
            this.Controladores_x_AreasDeTrabajo = new HashSet<Controladores_x_AreasDeTrabajo>();
            this.Cuenta_x_Controlador_x_Accion = new HashSet<Cuenta_x_Controlador_x_Accion>();
            this.Perfil_x_Controlador_x_Accion = new HashSet<Perfil_x_Controlador_x_Accion>();
        }
    
        public short Id_Controlador { get; set; }
        public string Nombre { get; set; }
        public bool Estatus { get; set; }
        public byte Id_Sistema { get; set; }
    
        public virtual ICollection<Accion_x_Controlador> Accion_x_Controlador { get; set; }
        public virtual ICollection<Controlador_x_AreasDeTrabajo> Controlador_x_AreasDeTrabajo { get; set; }
        public virtual Sistemas Sistemas { get; set; }
        public virtual ICollection<Controladores_x_AreasDeTrabajo> Controladores_x_AreasDeTrabajo { get; set; }
        public virtual ICollection<Cuenta_x_Controlador_x_Accion> Cuenta_x_Controlador_x_Accion { get; set; }
        public virtual ICollection<Perfil_x_Controlador_x_Accion> Perfil_x_Controlador_x_Accion { get; set; }
    }
}
