//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto
    {
        public Contacto()
        {
            this.Domicilios = new HashSet<Domicilios>();
            this.Personas = new HashSet<Personas>();
        }
    
        public int Id_Contacto { get; set; }
        public byte Id_ContactoTipo { get; set; }
        public string Contacto1 { get; set; }
        public byte Id_ContactoMedio { get; set; }
        public string Notas { get; set; }
        public bool Estatus { get; set; }
    
        public virtual Contacto_medio Contacto_medio { get; set; }
        public virtual Contacto_tipo Contacto_tipo { get; set; }
        public virtual ICollection<Domicilios> Domicilios { get; set; }
        public virtual ICollection<Personas> Personas { get; set; }
    }
}
