//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto_tipo
    {
        public Contacto_tipo()
        {
            this.Contacto = new HashSet<Contacto>();
            this.Domicilios = new HashSet<Domicilios>();
        }
    
        public byte Id_ContactoTipo { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Contacto> Contacto { get; set; }
        public virtual ICollection<Domicilios> Domicilios { get; set; }
    }
}
