//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contactos
    {
        public Contactos()
        {
            this.Contacto_x_Domicilio = new HashSet<Contacto_x_Domicilio>();
            this.Contacto_x_Persona = new HashSet<Contacto_x_Persona>();
        }
    
        public int Id_Contacto { get; set; }
        public byte Id_ContactoTipo { get; set; }
        public string Contacto { get; set; }
        public byte Id_ContactoMedio { get; set; }
        public string Notas { get; set; }
        public bool Estatus { get; set; }
    
        public virtual Contacto_medio Contacto_medio { get; set; }
        public virtual Contacto_tipo Contacto_tipo { get; set; }
        public virtual ICollection<Contacto_x_Domicilio> Contacto_x_Domicilio { get; set; }
        public virtual ICollection<Contacto_x_Persona> Contacto_x_Persona { get; set; }
    }
}
