//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Controladores_x_AreasDeTrabajo
    {
        public int Id { get; set; }
        public short Id_Controlador { get; set; }
        public short Id_AreaDeTrabajo { get; set; }
    
        public virtual AreasDeTrabajo AreasDeTrabajo { get; set; }
        public virtual Controladores Controladores { get; set; }
    }
}
