//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuentas
    {
        public Cuentas()
        {
            this.Benficio_x_Cuenta = new HashSet<Benficio_x_Cuenta>();
            this.Cuenta_x_AreasDeTrabajo_x_Accion = new HashSet<Cuenta_x_AreasDeTrabajo_x_Accion>();
            this.Cuenta_x_Controlador_x_Accion = new HashSet<Cuenta_x_Controlador_x_Accion>();
            this.Cuentas_x_Personas = new HashSet<Cuentas_x_Personas>();
            this.Equipos = new HashSet<Equipos>();
            this.MotivoBaja_x_Cuenta = new HashSet<MotivoBaja_x_Cuenta>();
            this.Sesiones = new HashSet<Sesiones>();
        }
    
        public int Id_Cuenta { get; set; }
        public int Id_Login { get; set; }
        public short Id_Perfil { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public byte IntentosCnn { get; set; }
        public Nullable<System.DateTime> InicioBloqueo { get; set; }
        public byte Id_Sistema { get; set; }
        public bool Estatus { get; set; }
        public byte Id_Baja { get; set; }
        public bool RegistroCompleto { get; set; }
    
        public virtual Baja Baja { get; set; }
        public virtual ICollection<Benficio_x_Cuenta> Benficio_x_Cuenta { get; set; }
        public virtual ICollection<Cuenta_x_AreasDeTrabajo_x_Accion> Cuenta_x_AreasDeTrabajo_x_Accion { get; set; }
        public virtual ICollection<Cuenta_x_Controlador_x_Accion> Cuenta_x_Controlador_x_Accion { get; set; }
        public virtual LogIn LogIn { get; set; }
        public virtual Perfiles Perfiles { get; set; }
        public virtual Sistemas Sistemas { get; set; }
        public virtual ICollection<Cuentas_x_Personas> Cuentas_x_Personas { get; set; }
        public virtual ICollection<Equipos> Equipos { get; set; }
        public virtual ICollection<MotivoBaja_x_Cuenta> MotivoBaja_x_Cuenta { get; set; }
        public virtual ICollection<Sesiones> Sesiones { get; set; }
    }
}
