//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Directorio_tipo
    {
        public Directorio_tipo()
        {
            this.Directorios = new HashSet<Directorios>();
        }
    
        public byte Id_DirectorioTipo { get; set; }
        public string Nombre { get; set; }
        public byte Id_Sistema { get; set; }
    
        public virtual Sistemas Sistemas { get; set; }
        public virtual ICollection<Directorios> Directorios { get; set; }
    }
}
