//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Directorios
    {
        public Directorios()
        {
            this.Directorios_x_Perfiles = new HashSet<Directorios_x_Perfiles>();
            this.Directorios_x_Sistemas = new HashSet<Directorios_x_Sistemas>();
        }
    
        public byte Id_Directorio { get; set; }
        public string Nombre { get; set; }
        public string Ruta { get; set; }
        public bool Estatus { get; set; }
        public byte Id_Sistema { get; set; }
    
        public virtual Sistemas Sistemas { get; set; }
        public virtual ICollection<Directorios_x_Perfiles> Directorios_x_Perfiles { get; set; }
        public virtual ICollection<Directorios_x_Sistemas> Directorios_x_Sistemas { get; set; }
    }
}
