//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genero
    {
        public Genero()
        {
            this.Personas = new HashSet<Personas>();
        }
    
        public byte Id_Genero { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Personas> Personas { get; set; }
    }
}
