//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogIn
    {
        public LogIn()
        {
            this.Cuentas = new HashSet<Cuentas>();
            this.Preguntas_x_Login = new HashSet<Preguntas_x_Login>();
        }
    
        public int Id_Login { get; set; }
        public string Usuario { get; set; }
        public string Senha { get; set; }
        public string Salt { get; set; }
        public bool UsoSalt { get; set; }
        public int Id_Persona { get; set; }
    
        public virtual ICollection<Cuentas> Cuentas { get; set; }
        public virtual Personas Personas { get; set; }
        public virtual ICollection<Preguntas_x_Login> Preguntas_x_Login { get; set; }
    }
}
