//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_categoria
    {
        public Menu_categoria()
        {
            this.Menu = new HashSet<Menu>();
        }
    
        public short Id_MenuCategoria { get; set; }
        public string Nombre { get; set; }
        public byte Orden { get; set; }
    
        public virtual ICollection<Menu> Menu { get; set; }
    }
}
