//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public short Id_Menu { get; set; }
        public string Nombre { get; set; }
        public short Parent { get; set; }
        public string Tooltip { get; set; }
        public short Id_Pagina { get; set; }
        public byte Orden { get; set; }
        public bool Habilitado { get; set; }
        public short Id_MenuCategoria { get; set; }
        public byte Id_Sistema { get; set; }
    
        public virtual Menu_categoria Menu_categoria { get; set; }
        public virtual Paginas Paginas { get; set; }
        public virtual Sistemas Sistemas { get; set; }
    }
}
