//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Municipios
    {
        public Municipios()
        {
            this.Domicilios = new HashSet<Domicilios>();
        }
    
        public short Id_Pais { get; set; }
        public short Id_Entidad { get; set; }
        public short Id_Municipio { get; set; }
        public string Nombre { get; set; }
        public string Abreviatura { get; set; }
    
        public virtual ICollection<Domicilios> Domicilios { get; set; }
        public virtual Entidades Entidades { get; set; }
    }
}
