//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paginas
    {
        public Paginas()
        {
            this.Menu = new HashSet<Menu>();
            this.Actividades = new HashSet<Actividades>();
        }
    
        public short Id_Pagina { get; set; }
        public string Nombre { get; set; }
        public string Titulo { get; set; }
        public byte Id_Sistema { get; set; }
    
        public virtual ICollection<Menu> Menu { get; set; }
        public virtual Sistemas Sistemas { get; set; }
        public virtual ICollection<Actividades> Actividades { get; set; }
    }
}
