//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paises
    {
        public Paises()
        {
            this.Entidades = new HashSet<Entidades>();
        }
    
        public short Id_Pais { get; set; }
        public string FIPS { get; set; }
        public string Nombre { get; set; }
        public byte Prioridad { get; set; }
    
        public virtual ICollection<Entidades> Entidades { get; set; }
    }
}
