//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametrosGpo_x_Beneficio
    {
        public int Id { get; set; }
        public byte Id_Beneficio { get; set; }
        public short Id_GpoParametro { get; set; }
    
        public virtual Beneficio Beneficio { get; set; }
        public virtual Parametros_grupo Parametros_grupo { get; set; }
    }
}
