//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros_configuracion
    {
        public short Id_ParametroGral { get; set; }
        public short Id_Parametro { get; set; }
        public Nullable<bool> Bit_v { get; set; }
        public Nullable<byte> TinyInt_v { get; set; }
        public Nullable<short> SmallInt_v { get; set; }
        public Nullable<int> Int_v { get; set; }
        public Nullable<decimal> Decimal_v { get; set; }
        public Nullable<System.DateTime> DateTime_v { get; set; }
        public Nullable<System.DateTime> SmallDateTime_v { get; set; }
        public string VarChar64_v { get; set; }
        public string VarChar128_v { get; set; }
        public System.Data.Entity.Spatial.DbGeography Geography_v { get; set; }
        public bool Estatus { get; set; }
        public byte Id_ParametroTipoDato { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public bool Caduca { get; set; }
        public Nullable<System.DateTime> Vigencia { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public byte Id_Sistema { get; set; }
        public byte Version { get; set; }
    
        public virtual Parametros Parametros { get; set; }
        public virtual Parametros_tipoDato Parametros_tipoDato { get; set; }
        public virtual Sistemas Sistemas { get; set; }
    }
}
