//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros
    {
        public Parametros()
        {
            this.Parametros_configuracion = new HashSet<Parametros_configuracion>();
            this.Parametros_mensaje = new HashSet<Parametros_mensaje>();
            this.Beneficio = new HashSet<Beneficio>();
        }
    
        public short Id_Parametro { get; set; }
        public string Nombre { get; set; }
        public byte Id_ParametroTipoDato { get; set; }
        public short Id_GpoParametro { get; set; }
        public byte Id_Sistema { get; set; }
    
        public virtual ICollection<Parametros_configuracion> Parametros_configuracion { get; set; }
        public virtual Parametros_grupo Parametros_grupo { get; set; }
        public virtual Parametros_tipoDato Parametros_tipoDato { get; set; }
        public virtual Sistemas Sistemas { get; set; }
        public virtual ICollection<Parametros_mensaje> Parametros_mensaje { get; set; }
        public virtual ICollection<Beneficio> Beneficio { get; set; }
    }
}
