//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros_configuracion
    {
        public short Id_ParametroGral { get; set; }
        public short Id_Parametro { get; set; }
        public string Valor { get; set; }
        public bool Estatus { get; set; }
        public byte Id_ParametroTipoDato { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public bool Caduca { get; set; }
        public Nullable<System.DateTime> Vigencia { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public byte Id_Sistema { get; set; }
        public byte Version { get; set; }
    
        public virtual Parametros Parametros { get; set; }
        public virtual Parametros_tipoDato Parametros_tipoDato { get; set; }
        public virtual Sistemas Sistemas { get; set; }
    }
}
