//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros_grupo
    {
        public Parametros_grupo()
        {
            this.Parametros = new HashSet<Parametros>();
            this.ParametrosGpo_x_Beneficio = new HashSet<ParametrosGpo_x_Beneficio>();
            this.ParametrosGpo_x_Perfiles = new HashSet<ParametrosGpo_x_Perfiles>();
        }
    
        public short Id_GpoParametro { get; set; }
        public string Nombre { get; set; }
        public byte Id_Sistema { get; set; }
    
        public virtual ICollection<Parametros> Parametros { get; set; }
        public virtual Sistemas Sistemas { get; set; }
        public virtual ICollection<ParametrosGpo_x_Beneficio> ParametrosGpo_x_Beneficio { get; set; }
        public virtual ICollection<ParametrosGpo_x_Perfiles> ParametrosGpo_x_Perfiles { get; set; }
    }
}
