//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros_tipoDato
    {
        public Parametros_tipoDato()
        {
            this.Parametros = new HashSet<Parametros>();
            this.Parametros_configuracion = new HashSet<Parametros_configuracion>();
        }
    
        public byte Id_ParametroTipoDato { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Parametros> Parametros { get; set; }
        public virtual ICollection<Parametros_configuracion> Parametros_configuracion { get; set; }
    }
}
