//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfiles
    {
        public Perfiles()
        {
            this.Beneficio_x_Perfiles = new HashSet<Beneficio_x_Perfiles>();
            this.Cuentas = new HashSet<Cuentas>();
            this.Permisos_Perfiles_x_Actividades = new HashSet<Permisos_Perfiles_x_Actividades>();
            this.AreasDeTrabajo = new HashSet<AreasDeTrabajo>();
            this.Directorios = new HashSet<Directorios>();
            this.Parametros_grupo = new HashSet<Parametros_grupo>();
        }
    
        public short Id_Perfil { get; set; }
        public string Nombre { get; set; }
        public string Funcion { get; set; }
        public string Tipo { get; set; }
        public string Nivel { get; set; }
        public byte Id_Sistema { get; set; }
    
        public virtual ICollection<Beneficio_x_Perfiles> Beneficio_x_Perfiles { get; set; }
        public virtual ICollection<Cuentas> Cuentas { get; set; }
        public virtual Sistemas Sistemas { get; set; }
        public virtual ICollection<Permisos_Perfiles_x_Actividades> Permisos_Perfiles_x_Actividades { get; set; }
        public virtual ICollection<AreasDeTrabajo> AreasDeTrabajo { get; set; }
        public virtual ICollection<Directorios> Directorios { get; set; }
        public virtual ICollection<Parametros_grupo> Parametros_grupo { get; set; }
    }
}
