//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permisos_AreaDeTrabajo_x_Cuenta
    {
        public int Id_Cuenta { get; set; }
        public short Id_AreaDeTrabajo { get; set; }
        public byte Id_Permiso { get; set; }
    
        public virtual AreasDeTrabajo AreasDeTrabajo { get; set; }
        public virtual Cuentas Cuentas { get; set; }
        public virtual Permisos Permisos { get; set; }
    }
}
