//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permisos
    {
        public Permisos()
        {
            this.Permisos_AreaDeTrabajo_x_Cuenta = new HashSet<Permisos_AreaDeTrabajo_x_Cuenta>();
            this.Permisos_Cuentas_x_Actividades = new HashSet<Permisos_Cuentas_x_Actividades>();
            this.Permisos_Perfiles_x_Actividades = new HashSet<Permisos_Perfiles_x_Actividades>();
        }
    
        public byte Id_Permiso { get; set; }
        public string Nombre { get; set; }
        public bool Estatus { get; set; }
    
        public virtual ICollection<Permisos_AreaDeTrabajo_x_Cuenta> Permisos_AreaDeTrabajo_x_Cuenta { get; set; }
        public virtual ICollection<Permisos_Cuentas_x_Actividades> Permisos_Cuentas_x_Actividades { get; set; }
        public virtual ICollection<Permisos_Perfiles_x_Actividades> Permisos_Perfiles_x_Actividades { get; set; }
    }
}
