//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personas
    {
        public Personas()
        {
            this.Contacto_x_Persona = new HashSet<Contacto_x_Persona>();
            this.Cuentas_x_Personas = new HashSet<Cuentas_x_Personas>();
            this.Domicilio_x_Personas = new HashSet<Domicilio_x_Personas>();
        }
    
        public int Id_Persona { get; set; }
        public string APaterno { get; set; }
        public string AMaterno { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string Email { get; set; }
        public byte Id_Genero { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string RFC { get; set; }
        public string Homoclave { get; set; }
        public string CURP { get; set; }
        public string Foto { get; set; }
        public bool Estatus { get; set; }
    
        public virtual ICollection<Contacto_x_Persona> Contacto_x_Persona { get; set; }
        public virtual ICollection<Cuentas_x_Personas> Cuentas_x_Personas { get; set; }
        public virtual ICollection<Domicilio_x_Personas> Domicilio_x_Personas { get; set; }
        public virtual Genero Genero { get; set; }
    }
}
