//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preguntas_x_Cuentas
    {
        public int Id { get; set; }
        public int Id_Cuenta { get; set; }
        public byte Id_Pregunta { get; set; }
        public string Respuesta { get; set; }
    
        public virtual Cuentas Cuentas { get; set; }
        public virtual Preguntas Preguntas { get; set; }
    }
}
