//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SecurityEntities : DbContext
    {
        public SecurityEntities()
            : base("name=SecurityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accion_x_Controlador> Accion_x_Controlador { get; set; }
        public virtual DbSet<Acciones> Acciones { get; set; }
        public virtual DbSet<AreasDeTrabajo> AreasDeTrabajo { get; set; }
        public virtual DbSet<AreasDeTrabajo_x_Perfiles> AreasDeTrabajo_x_Perfiles { get; set; }
        public virtual DbSet<Baja> Baja { get; set; }
        public virtual DbSet<Baja_motivos> Baja_motivos { get; set; }
        public virtual DbSet<Beneficio> Beneficio { get; set; }
        public virtual DbSet<Beneficio_tipo> Beneficio_tipo { get; set; }
        public virtual DbSet<Beneficio_x_AreaDeTrabajo> Beneficio_x_AreaDeTrabajo { get; set; }
        public virtual DbSet<Beneficio_x_Perfiles> Beneficio_x_Perfiles { get; set; }
        public virtual DbSet<Benficio_x_Cuenta> Benficio_x_Cuenta { get; set; }
        public virtual DbSet<Contacto_medio> Contacto_medio { get; set; }
        public virtual DbSet<Contacto_tipo> Contacto_tipo { get; set; }
        public virtual DbSet<Contacto_x_Domicilio> Contacto_x_Domicilio { get; set; }
        public virtual DbSet<Contacto_x_Persona> Contacto_x_Persona { get; set; }
        public virtual DbSet<Contactos> Contactos { get; set; }
        public virtual DbSet<Controlador_x_AreasDeTrabajo> Controlador_x_AreasDeTrabajo { get; set; }
        public virtual DbSet<Controladores> Controladores { get; set; }
        public virtual DbSet<Controladores_x_AreasDeTrabajo> Controladores_x_AreasDeTrabajo { get; set; }
        public virtual DbSet<Cuenta_x_AreasDeTrabajo_x_Accion> Cuenta_x_AreasDeTrabajo_x_Accion { get; set; }
        public virtual DbSet<Cuenta_x_Controlador_x_Accion> Cuenta_x_Controlador_x_Accion { get; set; }
        public virtual DbSet<Cuentas> Cuentas { get; set; }
        public virtual DbSet<Cuentas_x_Personas> Cuentas_x_Personas { get; set; }
        public virtual DbSet<Directorios> Directorios { get; set; }
        public virtual DbSet<Directorios_x_Perfiles> Directorios_x_Perfiles { get; set; }
        public virtual DbSet<Directorios_x_Sistemas> Directorios_x_Sistemas { get; set; }
        public virtual DbSet<Dispositivos_tipo> Dispositivos_tipo { get; set; }
        public virtual DbSet<Domicilio_x_Personas> Domicilio_x_Personas { get; set; }
        public virtual DbSet<Domicilios> Domicilios { get; set; }
        public virtual DbSet<Entidades> Entidades { get; set; }
        public virtual DbSet<Equipos> Equipos { get; set; }
        public virtual DbSet<Equipos_tipo> Equipos_tipo { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<Genero> Genero { get; set; }
        public virtual DbSet<Locations> Locations { get; set; }
        public virtual DbSet<MotivoBaja_x_Cuenta> MotivoBaja_x_Cuenta { get; set; }
        public virtual DbSet<Municipios> Municipios { get; set; }
        public virtual DbSet<Paises> Paises { get; set; }
        public virtual DbSet<Parametros> Parametros { get; set; }
        public virtual DbSet<Parametros_configuracion> Parametros_configuracion { get; set; }
        public virtual DbSet<Parametros_grupo> Parametros_grupo { get; set; }
        public virtual DbSet<Parametros_mensaje> Parametros_mensaje { get; set; }
        public virtual DbSet<Parametros_tipoDato> Parametros_tipoDato { get; set; }
        public virtual DbSet<Parametros_x_Beneficio> Parametros_x_Beneficio { get; set; }
        public virtual DbSet<ParametrosGpo_x_Beneficio> ParametrosGpo_x_Beneficio { get; set; }
        public virtual DbSet<ParametrosGpo_x_Perfiles> ParametrosGpo_x_Perfiles { get; set; }
        public virtual DbSet<Perfil_x_Controlador_x_Accion> Perfil_x_Controlador_x_Accion { get; set; }
        public virtual DbSet<Perfiles> Perfiles { get; set; }
        public virtual DbSet<Personas> Personas { get; set; }
        public virtual DbSet<Preguntas> Preguntas { get; set; }
        public virtual DbSet<Preguntas_x_Cuentas> Preguntas_x_Cuentas { get; set; }
        public virtual DbSet<Sesiones> Sesiones { get; set; }
        public virtual DbSet<Sistemas> Sistemas { get; set; }
    }
}
