//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sistemas
    {
        public Sistemas()
        {
            this.AreasDeTrabajo = new HashSet<AreasDeTrabajo>();
            this.Controladores = new HashSet<Controladores>();
            this.Cuentas = new HashSet<Cuentas>();
            this.Directorios = new HashSet<Directorios>();
            this.Directorios_x_Sistemas = new HashSet<Directorios_x_Sistemas>();
            this.Equipos = new HashSet<Equipos>();
            this.Parametros = new HashSet<Parametros>();
            this.Parametros_configuracion = new HashSet<Parametros_configuracion>();
            this.Parametros_grupo = new HashSet<Parametros_grupo>();
            this.Perfiles = new HashSet<Perfiles>();
            this.Sesiones = new HashSet<Sesiones>();
        }
    
        public byte Id_Sistema { get; set; }
        public string Nombre { get; set; }
        public string Siglas { get; set; }
        public string Descripcion { get; set; }
        public bool Estatus { get; set; }
    
        public virtual ICollection<AreasDeTrabajo> AreasDeTrabajo { get; set; }
        public virtual ICollection<Controladores> Controladores { get; set; }
        public virtual ICollection<Cuentas> Cuentas { get; set; }
        public virtual ICollection<Directorios> Directorios { get; set; }
        public virtual ICollection<Directorios_x_Sistemas> Directorios_x_Sistemas { get; set; }
        public virtual ICollection<Equipos> Equipos { get; set; }
        public virtual ICollection<Parametros> Parametros { get; set; }
        public virtual ICollection<Parametros_configuracion> Parametros_configuracion { get; set; }
        public virtual ICollection<Parametros_grupo> Parametros_grupo { get; set; }
        public virtual ICollection<Perfiles> Perfiles { get; set; }
        public virtual ICollection<Sesiones> Sesiones { get; set; }
    }
}
